struct  Solution;
impl Solution {
    pub fn generate_key(num1: i32, num2: i32, num3: i32) -> i32 {
        let num1_str = check_length(num1.to_string());
        let num2_str = check_length(num2.to_string());
        let num3_str = check_length(num3.to_string());

        let num1_str = num1_str.chars().collect::<Vec<char>>();
        let num2_str = num2_str.chars().collect::<Vec<char>>();
        let num3_str = num3_str.chars().collect::<Vec<char>>();
        let mut  stri = String::new();
        for i in 0..4 {
            let s = compare(num1_str[i], num2_str[i], num3_str[i]);
            stri.push_str(&s.to_string());
        }
        i32::from_str_radix(&stri, 10).unwrap()
    }
}
fn compare (n1:char,n2:char,n3:char)-> i32{
    let vec = vec![
        i32::from_str_radix(&n1.to_string(), 10).unwrap(),
        i32::from_str_radix(&n2.to_string(), 10).unwrap(),
        i32::from_str_radix(&n3.to_string(), 10).unwrap()];
        let r = vec.iter().min().unwrap();
        *r
}
fn check_length(string: String)->String{
    let mut result = String::new();
    if string.len() >= 4 {
        return string;
    }else {
        let mut len = string.len();
        result = string.clone(); 
        while len < 4 {
            result.insert(0, '0');
            len +=1;
        }
    }
    result
}
fn main() {
    println!("Hello, world!");
}


/*

3270. Find the Key of the Numbers
Easy

You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:

Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).

 

Example 1:

Input: num1 = 1, num2 = 10, num3 = 1000

Output: 0

Explanation:

On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

The 1st digit of the key is min(0, 0, 1).
The 2nd digit of the key is min(0, 0, 0).
The 3rd digit of the key is min(0, 1, 0).
The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.

Example 2:

Input: num1 = 987, num2 = 879, num3 = 798

Output: 777

Example 3:

Input: num1 = 1, num2 = 2, num3 = 3

Output: 1

 

Constraints:

1 <= num1, num2, num3 <= 9999*/